# Generated by Django 5.2.8 on 2025-11-17 18:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default='BAIRRO PENDENTE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='Jacobina', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(default='Bahia', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default='PENDENTE', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(default='RUA PENDENTE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='aluno',
            name='whatsapp',
            field=models.CharField(default='00000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáàâãéèêíìîóòôõúùûçÇÁÀÂÃÉÈÊÍÌÎÓÒÔÕÚÙÛ\\s]*$', 'Apenas letras são permitidas neste campo.')]),
        ),
        migrations.AddField(
            model_name='aluno',
            name='modalidades',
            field=models.ManyToManyField(to='alunos.modalidade'),
        ),
    ]
