# Generated by Django 5.2.8 on 2025-11-19 01:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_options_alter_aluno_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(default=datetime.date.today)),
                ('data_vencimento', models.DateField()),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito/Débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20)),
                ('pago', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
