# Generated by Django 5.2.8 on 2025-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
